### ISSUE TITLE
Analytics Utility for tracking client side events

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-eclipse-tools#139] opened 2016-05-05 14:02 UTC
Via GA: likely along the lines of AnalyticsPingManager in the old plugin though hopefully simpler

**Comment by chanseokoh** [comment] 2016-05-09 15:21
As mentioned in #142, I'm thinking of using [https://github.com/google/cloud-reporting](https://github.com/google/cloud-reporting) since it's what the Concord and the DI Metrics teams offer for client-side Java (according to their docs).

We need to hide an AnalyticsID in the codebase though.

**Comment by chanseokoh** [comment] 2016-05-09 16:27
If you prefer, we can use AnalyticsPingManager from the old plugin.

However, some modifications are necessary because we will send pings to the Concord GA property (i.e., not to our own GA properties). Unlike our old GPE and CT4IJ, this Concord Analytics ID is set up as a "web" type instead of an "Android app" type (because it was designed to accommodate metrics from all Cloud products).

- Mainly, we need to send a 'pageview' ping ([should be `t=pageview`](https://github.com/google/cloud-reporting/blob/master/src/main/java/com/google/cloud/metrics/MetricsUtils.java#L73)) instead of an 'event' ping ([currently, it is `t=event` in AnalyticsPingManager](https://github.com/GoogleCloudPlatform/google-plugin-for-eclipse/blob/master/plugins/com.google.gdt.eclipse.suite.update/src/com/google/gdt/eclipse/suite/update/usage/AnalyticsPingManager.java#L183)).
  - For example, this requires a virtual "web" URL and a virtual "webpage" title.
- That said, we need to follow the contract/interface that Concord wants.
  - Some custom dimensions (mostly optional though).
  - A complete example can be found [here](https://github.com/google/cloud-reporting/blob/master/src/main/java/com/google/cloud/metrics/MetricsUtils.java#L64) (the library that Concord offers).

**Comment by patflynn** [comment] 2016-05-23 14:15
Why not use the cloud-reporting project for this?

**Comment by chanseokoh** [comment] 2016-05-23 14:56
We had a very brief discussion, and the general consensus was that

- Making our code depend on an external library, particularly if it is not published into the Maven Central, seems a bad idea. In fact, the library is not actively maintained.

- Nevertheless, a small piece of code (possibly a single class) will do the job, so it is ok in whatever ways this is done even though it may result in duplicate code in IntelliJ and Eclipse.

**Comment by chanseokoh** [comment] 2016-06-10 19:37
Closed by #216.

**Closed by chanseokoh** 2016-06-10 19:37 UTC
Labels: enhancement, ready
